### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by kasperjha** [xtotdam/dynmap-assemble#4]
Looks like a great script, but cant get it working on either `python2.7` or `python3.7`
I have installed both `pillow-8.1.0` and `tqdm-4.58.0` on 2.7 and 3.9

```
$ python dynmap-assemble.py
Traceback (most recent call last):
  File "dynmap-assemble.py", line 54, in <module>
    elif bg_key.startswith('#') and len(bg_key) == 7:
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by kasperjha** [comment]
Nevermind, just me being retarded 
Forgot to add interactive flag
